<a href="https://colab.research.google.com/github/sumitmsc/PythonPractice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
!pip install numpy

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr,type(arr))


[1 2 3 4 5] <class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr1=np.array((1,2,3,4,5))
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [ ]:
#0d
import numpy as np
arr=np.array(42)
print(arr,type(arr))
a=42
print(a,type(a),arr.ndim)

42 <class 'numpy.ndarray'>
42 <class 'int'> 0


In [ ]:
#1d
import numpy as np
arr=np.array([1,2,3,4])
print(arr,type(arr),arr.ndim)


[1 2 3 4] <class 'numpy.ndarray'> 1


In [ ]:
#2d
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])#Nested List
print(arr,type(arr),arr.ndim)

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> 2


In [ ]:
#3d
import numpy as np
arr=np.array([[[1,2,3],[5,6,7]],[[1,2,3],[5,6,7]],[[1,2,3],[5,6,7]]])#Nested List
print(arr,type(arr),arr.ndim)

[[[1 2 3]
  [5 6 7]]

 [[1 2 3]
  [5 6 7]]

 [[1 2 3]
  [5 6 7]]] <class 'numpy.ndarray'> 3


In [ ]:
#ND
import numpy as np
arr=np.array([1,2,3,4,5], ndmin=5)
print(arr,type(arr),arr.ndim)

[[[[[1 2 3 4 5]]]]] <class 'numpy.ndarray'> 5


In [ ]:
#Accessing the array
import numpy as np
arr1=np.array((1,2,3,4,5))
print(arr1[0],arr1[1])


1 2


In [ ]:
'''Write a code which will check weather an array is having same elements from left to right or right to left
1234321 =yes
12234=no
'''
import numpy as np

arr1=np.array((1,2,3,4))
print(arr1,type(arr1),arr1.ndim)

for i in arr1:
  print(i)




[1 2 3 4] <class 'numpy.ndarray'> 1
1
2
3
4


In [ ]:
'''Write a code which will check weather an array is having same elements from left to right or right to left
1234321 =yes
12234=no
'''
l=[1,2,3,2,1]
for i in range(len(l)//2+1):
  if l[i]!=l[-(i+1)]:
   print('Not equal')
   break

else:
     print('list is palindrom ')






list is palindrom 


In [ ]:
#Accessing 2D array
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print('elements')
print(arr[0,0])
print(arr[0,-1])
print(arr[1,-2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
elements
1
5
9


In [11]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr,arr.shape)
print(arr[1:3])
print(arr[::-1])

[1 2 3 4 5] (5,)
[2 3]
[5 4 3 2 1]


In [16]:
#Checking data type
arr=np.array([1,2,3,4])
arr1=np.array(['apple','bananajjj','grapes'])
arr2=np.array(['a','b'])
print(arr,arr.dtype)
print(arr1,arr1.dtype)
print(arr2,arr2.dtype)

[1 2 3 4] int64
['apple' 'bananajjj' 'grapes'] <U9
['a' 'b'] <U1


In [23]:
#Creating arrays with the deffined data type

import numpy as np

arr=np.array([1,24,3,4,5], dtype='S')
print(arr,arr.dtype)

[b'1' b'24' b'3' b'4' b'5'] |S2


In [24]:
#Creating arrays with the deffined size of int

import numpy as np

arr=np.array([1,24,3,4,5], dtype=np.int8)
print(arr,arr.dtype)

[ 1 24  3  4  5] int8


In [32]:
#float to int
a=[1.2,1.3,5.6,7.8]
new_a=np.array(a)
new_int=new_a.astype(int)
print(new_int,new_int.dtype)

[1 1 5 7] int64


In [34]:
#Array rreshape

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
n=arr.reshape(3,4)
print(n,n.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 2


In [40]:
# 2 d to 1 d using reshape (-1) :Flattening the aarrya converting multidimensional array to 1 D array
import numpy as np

arr=np.array(([1,2,3,4,5],[6,7,8,9,10]))
print(arr)
new_arr=arr.reshape(-1)
print(new_arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [55]:
#Iterating an array: going through elements one by one.
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr,arr.ndim)
print(type(arr[0]))
print("Data type:", arr.dtype)
print(type(arr))
for i in arr:
  print(i)


[ 1  2  3  4  5  6  7  8  9 10 11 12] 1
<class 'numpy.int64'>
Data type: int64
<class 'numpy.ndarray'>
1
2
3
4
5
6
7
8
9
10
11
12


Great question! Here's why NumPy accepts 'test':
What's happening:
NumPy arrays must have a single data type for all elements. When you mix integers and a string, NumPy converts everything to the "lowest common denominator" - which is strings!

In [52]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 'test'])
print(arr)
# Output: ['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' 'test']

print("Data type:", arr.dtype)  # <-- Check this!
# Output: <U21 (Unicode string)

# Now your integers are strings!
print(type(arr[0]))  # <class 'numpy.str_'>
print(arr[0] + arr[1])  # '12' not 3! (string concatenation)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' 'test']
Data type: <U21
<class 'numpy.str_'>
12


Great question! Let me explain with examples:
"Lowest common denominator" in NumPy means the data type that can hold ALL the values without losing information.
Think of it like a hierarchy:

string (most flexible - can hold anything)
  ↑
float (can hold decimals and whole numbers)
  ↑
int (can only hold whole numbers)
  ↑
bool (can only hold True/False)


The Rule:
NumPy always picks the type that can represent all your data. String wins because it can represent anything (numbers, text, symbols), but you lose the ability to do math!
Think of it like packing boxes - you need a box big enough to fit everything, even if most items are small! 📦
Does that make sense?

In [56]:
import numpy as np

# Example 1: int + float → float
arr1 = np.array([1, 2, 3.5])
print(arr1.dtype)  # float64
# Why? 3.5 needs decimals, so ALL become floats: [1.0, 2.0, 3.5]

# Example 2: int + string → string
arr2 = np.array([1, 2, 'hello'])
print(arr2.dtype)  # <U21 (string)
# Why? 'hello' can't be a number, so ALL become strings: ['1', '2', 'hello']

# Example 3: bool + int → int
arr3 = np.array([True, False, 5])
print(arr3.dtype)  # int64
# Result: [1, 0, 5] - bools converted to 1s and 0s

# Example 4: All ints stay ints
arr4 = np.array([1, 2, 3, 4])
print(arr4.dtype)  # int64
# Perfect! No conversion needed

float64
<U21
int64
int64


🧩 What Does Iterating an Array Mean?

Iteration simply means going through each element (or sub-array) in an array, one by one — just like looping over a list.

In Python:
 Iterating 1d num py
import numpy as np

arr = np.array([10, 20, 30, 40])

for x in arr:
    print(x)


In [57]:
import numpy as np

arr = np.array([10, 20, 30, 40])

for x in arr:
    print(x)


10
20
30
40


In [64]:
#2D array and sum of all elements
import numpy as np

arr=np.array([[1,2,4],[5,6,7]])
print(arr.ndim)
print(type(arr))
print('Shape of array',arr.shape)
for i  in arr:
  print(i)
print(sum(i))


2
<class 'numpy.ndarray'>
Shape of array (2, 3)
[1 2 4]
[5 6 7]
18
